export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  UNPROCESSABLE = 'UNPROCESSABLE',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  ADMISSION_FEE_PENDING = 'ADMISSION_FEE_PENDING',
  PARTIAL_PAYMENT_NOT_ALLOWED = 'PARTIAL_PAYMENT_NOT_ALLOWED',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  SHIFT_CAP_EXCEEDED = 'SHIFT_CAP_EXCEEDED',
  TEACHER_NOT_IN_SHIFT = 'TEACHER_NOT_IN_SHIFT',
  SHIFT_MISMATCH = 'SHIFT_MISMATCH',
  STUDENT_NOT_ACTIVE = 'STUDENT_NOT_ACTIVE',
  STUDENT_ALREADY_MAPPED = 'STUDENT_ALREADY_MAPPED',
  MAPPING_EXISTS = 'MAPPING_EXISTS',
  SUBSTITUTE_UNAVAILABLE = 'SUBSTITUTE_UNAVAILABLE',
  DATE_IS_HOLIDAY = 'DATE_IS_HOLIDAY',
  FUTURE_DATE = 'FUTURE_DATE',
  OUT_OF_ENROLLMENT_RANGE = 'OUT_OF_ENROLLMENT_RANGE',
  ATTENDANCE_FROZEN = 'ATTENDANCE_FROZEN',
  INSUFFICIENT_LEAVE_BALANCE = 'INSUFFICIENT_LEAVE_BALANCE',
  OVERLAPPING_LEAVE = 'OVERLAPPING_LEAVE',
  MEDICAL_CERTIFICATE_REQUIRED = 'MEDICAL_CERTIFICATE_REQUIRED',
  ACTIVE_IEP_EXISTS = 'ACTIVE_IEP_EXISTS',
  IEP_NOT_EDITABLE = 'IEP_NOT_EDITABLE',
  IEP_INCOMPLETE = 'IEP_INCOMPLETE',
  INVALID_REPORT_TRANSITION = 'INVALID_REPORT_TRANSITION',
  REPORT_EXISTS = 'REPORT_EXISTS',
  NO_TEMPLATE = 'NO_TEMPLATE',
  GOAL_LINK_REQUIRED = 'GOAL_LINK_REQUIRED',
  OVERPAYMENT = 'OVERPAYMENT',
  INVOICE_HAS_PAYMENTS = 'INVOICE_HAS_PAYMENTS',
  OPTIN_CLOSED = 'OPTIN_CLOSED',
  BACKDATED_REQUEST = 'BACKDATED_REQUEST',
  SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT',
  THERAPIST_NOT_ACTIVE = 'THERAPIST_NOT_ACTIVE',
  PATIENT_NOT_ACTIVE = 'PATIENT_NOT_ACTIVE',
  GROUP_FULL = 'GROUP_FULL',
  GROUP_CLOSED = 'GROUP_CLOSED',
  ALREADY_ENROLLED = 'ALREADY_ENROLLED',
  NOT_ENROLLED = 'NOT_ENROLLED',
  SESSION_NOT_CANCELLABLE = 'SESSION_NOT_CANCELLABLE',
  SESSION_ALREADY_COMPLETED = 'SESSION_ALREADY_COMPLETED',
  ACTIVE_TREATMENT_PLAN_EXISTS = 'ACTIVE_TREATMENT_PLAN_EXISTS',
  TREATMENT_PLAN_NOT_EDITABLE = 'TREATMENT_PLAN_NOT_EDITABLE',
  THERAPY_INVOICE_HAS_PAYMENTS = 'THERAPY_INVOICE_HAS_PAYMENTS',
  SERIES_CAP_EXCEEDED = 'SERIES_CAP_EXCEEDED',
  RECURRENCE_ENDED = 'RECURRENCE_ENDED',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  UNSUPPORTED_THERAPY_TYPE = 'UNSUPPORTED_THERAPY_TYPE',
  JOURNAL_UNBALANCED = 'JOURNAL_UNBALANCED',
  INVALID_ACCOUNT = 'INVALID_ACCOUNT',
  PERIOD_CLOSED = 'PERIOD_CLOSED',
  SELF_APPROVAL_FORBIDDEN = 'SELF_APPROVAL_FORBIDDEN',
  JOURNAL_IMMUTABLE = 'JOURNAL_IMMUTABLE',
  POSTING_RULE_MISSING = 'POSTING_RULE_MISSING',
  COST_CENTER_REQUIRED = 'COST_CENTER_REQUIRED',
  TRANSACTION_REQUIRED = 'TRANSACTION_REQUIRED',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  VOUCHER_POSTED = 'VOUCHER_POSTED',
  INVALID_CHEQUE_TRANSITION = 'INVALID_CHEQUE_TRANSITION',
  RECONCILIATION_UNBALANCED = 'RECONCILIATION_UNBALANCED',
  INSUFFICIENT_CASH = 'INSUFFICIENT_CASH',
  SHARE_PERCENTAGE_INVALID = 'SHARE_PERCENTAGE_INVALID',
  INSUFFICIENT_SHARES = 'INSUFFICIENT_SHARES',
  ALLOCATION_EXCEEDS_PROFIT = 'ALLOCATION_EXCEEDS_PROFIT',
  PERIOD_NOT_CLOSED = 'PERIOD_NOT_CLOSED',
  STRUCTURE_NOT_APPROVED = 'STRUCTURE_NOT_APPROVED',
  PAYROLL_RUN_EXISTS = 'PAYROLL_RUN_EXISTS',
  PAYROLL_LOCKED = 'PAYROLL_LOCKED',
  RUN_NOT_APPROVED = 'RUN_NOT_APPROVED',
  PAYROLL_NOT_LOCKED = 'PAYROLL_NOT_LOCKED',
  NEGATIVE_NET_PAY = 'NEGATIVE_NET_PAY',
  EXIT_RECORD_MISSING = 'EXIT_RECORD_MISSING',
  ALREADY_SETTLED = 'ALREADY_SETTLED',
  LEAVE_TYPE_NOT_ENCASHABLE = 'LEAVE_TYPE_NOT_ENCASHABLE',
  EXCEEDS_ELIGIBLE_DAYS = 'EXCEEDS_ELIGIBLE_DAYS',
  DEADLINE_PASSED = 'DEADLINE_PASSED',
  SELF_REVIEW_FORBIDDEN = 'SELF_REVIEW_FORBIDDEN',
  KPI_WEIGHTS_INVALID = 'KPI_WEIGHTS_INVALID',
  INVALID_STAGE_TRANSITION = 'INVALID_STAGE_TRANSITION',
  NO_OPEN_POSITION = 'NO_OPEN_POSITION',
  OFFER_NOT_ACCEPTED = 'OFFER_NOT_ACCEPTED',
  CAPACITY_FULL = 'CAPACITY_FULL',
  NOT_ATTENDED = 'NOT_ATTENDED',
  // Phase 6 — Inventory / Procurement
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  BATCH_EXPIRED = 'BATCH_EXPIRED',
  ASSET_ALREADY_ASSIGNED = 'ASSET_ALREADY_ASSIGNED',
  ASSET_DISPOSED = 'ASSET_DISPOSED',
  AUDIT_INCOMPLETE = 'AUDIT_INCOMPLETE',
  EXPLANATION_REQUIRED = 'EXPLANATION_REQUIRED',
  AUDIT_SIGNED_OFF = 'AUDIT_SIGNED_OFF',
  INVALID_PR_TRANSITION = 'INVALID_PR_TRANSITION',
  PR_NOT_APPROVED = 'PR_NOT_APPROVED',
  NO_REMAINING_QUANTITY = 'NO_REMAINING_QUANTITY',
  EXCEEDS_REQUESTED_QUANTITY = 'EXCEEDS_REQUESTED_QUANTITY',
  VENDOR_UNAVAILABLE = 'VENDOR_UNAVAILABLE',
  PO_APPROVAL_REQUIRED = 'PO_APPROVAL_REQUIRED',
  PO_NOT_APPROVED = 'PO_NOT_APPROVED',
  PO_PARTIALLY_RECEIVED = 'PO_PARTIALLY_RECEIVED',
  PO_NOT_RECEIVABLE = 'PO_NOT_RECEIVABLE',
  EXCEEDS_ORDERED_QUANTITY = 'EXCEEDS_ORDERED_QUANTITY',
  GRN_ALREADY_POSTED = 'GRN_ALREADY_POSTED',
  EXPIRY_REQUIRED = 'EXPIRY_REQUIRED',
  SERIAL_COUNT_MISMATCH = 'SERIAL_COUNT_MISMATCH',
  ITEM_REQUIRED = 'ITEM_REQUIRED',
  INVOICE_VARIANCE_EXCEEDED = 'INVOICE_VARIANCE_EXCEEDED',
  EXCEEDS_ACCEPTED_QUANTITY = 'EXCEEDS_ACCEPTED_QUANTITY',
  ALLOCATION_MISMATCH = 'ALLOCATION_MISMATCH',
  EXCEEDS_ADVANCE = 'EXCEEDS_ADVANCE',
  VENDOR_BLACKLISTED = 'VENDOR_BLACKLISTED',
  // Phase 7 — Reports & Dashboards
  RANGE_TOO_LARGE = 'RANGE_TOO_LARGE',
  REPORT_TIMEOUT = 'REPORT_TIMEOUT',
  EXPORT_TOO_LARGE = 'EXPORT_TOO_LARGE',
  INVALID_SELECTION = 'INVALID_SELECTION',
  // Phase 8 — Notifications & Messaging
  TEMPLATE_VARIABLE_MISSING = 'TEMPLATE_VARIABLE_MISSING',
  EDIT_WINDOW_EXPIRED = 'EDIT_WINDOW_EXPIRED',
  NO_APPROVER_RESOLVED = 'NO_APPROVER_RESOLVED',
  SESSION_IDLE_TIMEOUT = 'SESSION_IDLE_TIMEOUT',
}

export class DomainException extends Error {
  constructor(
    public readonly code: ErrorCode,
    public readonly statusCode: number,
    message: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'DomainException';
  }

  static invalidCredentials(message = 'Invalid username or password') {
    return new DomainException(ErrorCode.INVALID_CREDENTIALS, 401, message);
  }

  static locked(message = 'Account is temporarily locked') {
    return new DomainException(ErrorCode.ACCOUNT_LOCKED, 423, message);
  }

  static forbidden(message = 'Forbidden', code = ErrorCode.FORBIDDEN) {
    return new DomainException(code, 403, message);
  }

  static notFound(message = 'Not found') {
    return new DomainException(ErrorCode.NOT_FOUND, 404, message);
  }

  static conflict(message: string) {
    return new DomainException(ErrorCode.CONFLICT, 409, message);
  }

  static validation(message: string, details?: Record<string, unknown>) {
    return new DomainException(
      ErrorCode.VALIDATION_ERROR,
      400,
      message,
      details,
    );
  }

  static unprocessable(message: string, details?: Record<string, unknown>) {
    return new DomainException(ErrorCode.UNPROCESSABLE, 422, message, details);
  }

  static withCode(
    code: ErrorCode,
    statusCode: number,
    message: string,
    details?: Record<string, unknown>,
  ) {
    return new DomainException(code, statusCode, message, details);
  }
}
