/** @type {import('jest').Config} */
/** Unit-only config so coverage thresholds correctly fail the process (projects mode can swallow exit codes). */
module.exports = {
  displayName: 'unit',
  rootDir: '.',
  testMatch: ['<rootDir>/src/**/*.spec.ts'],
  testPathIgnorePatterns: ['\\.integration\\.spec\\.ts$'],
  transform: { '^.+\\.(t|j)s$': 'ts-jest' },
  moduleFileExtensions: ['js', 'json', 'ts'],
  testEnvironment: 'node',
  collectCoverageFrom: [
    'src/modules/auth/services/**/*.ts',
    'src/modules/accounts/services/accounts.service.ts',
    'src/modules/accounts/services/tax.service.ts',
    'src/modules/accounts/services/budget-check.service.ts',
    'src/modules/school/services/admission-fee.service.ts',
    'src/modules/school/services/fee-invoice.service.ts',
    'src/modules/school/services/fee-payment.service.ts',
    'src/modules/school/services/iep.service.ts',
    'src/modules/school/services/student-status.service.ts',
    'src/modules/school/services/working-days.service.ts',
    'src/modules/portal/services/portal-scope.service.ts',
    'src/modules/therapy/services/conflict-detection.service.ts',
    'src/modules/hr/services/payroll-calculation.service.ts',
    'src/modules/hr/services/gratuity-calculation.service.ts',
    'src/modules/hr/services/gratuity-settlement.service.ts',
    'src/modules/hr/services/encashment.service.ts',
    'src/modules/inventory/services/stock-valuation.service.ts',
    'src/modules/inventory/services/depreciation.service.ts',
    'src/modules/procurement/services/three-way-match.service.ts',
    'src/modules/notifications/services/channel-router.service.ts',
    'src/modules/notifications/services/template-renderer.service.ts',
    'src/modules/notifications/services/recipient-resolver.service.ts',
    'src/modules/notifications/services/approval-chain.service.ts',
    'src/modules/hardening/services/field-encryption.service.ts',
    'src/shared/money/**/*.ts',
    'src/shared/guards/permissions.guard.ts',
    'src/shared/guards/roles.guard.ts',
    'src/shared/errors/domain-exception.ts',
    'src/shared/ports/**/*.ts',
    'src/shared/events/event-names.ts',
    'src/shared/logger/sensitive-fields.serializer.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.module.ts',
    '!src/**/*.dto.ts',
  ],
  coverageDirectory: './coverage/unit',
  coverageReporters: ['text', 'text-summary', 'lcov', 'html', 'json-summary'],
  coverageThreshold: {
    global: {
      lines: 70,
      branches: 52,
      functions: 65,
      statements: 70,
    },
  },
  reporters: ['default'],
};
