/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
module.exports = {
  packageManager: 'npm',
  reporters: ['clear-text', 'progress'],
  testRunner: 'jest',
  coverageAnalysis: 'perTest',
  mutate: [
    'src/modules/auth/services/**/*.ts',
    'src/modules/school/services/student-status.service.ts',
    'src/modules/school/services/admission-fee.service.ts',
    'src/modules/school/services/teacher-mapping.service.ts',
    'src/modules/school/services/substitute.service.ts',
    'src/modules/school/services/school-attendance.service.ts',
    'src/modules/school/services/working-days.service.ts',
    'src/modules/school/services/iep.service.ts',
    'src/modules/school/services/progress-report.service.ts',
    'src/modules/school/services/fee-invoice.service.ts',
    'src/modules/school/services/fee-payment.service.ts',
    'src/modules/school/services/activity.service.ts',
    'src/modules/school/services/student-leave.service.ts',
    'src/modules/portal/services/portal-scope.service.ts',
    'src/modules/hr/services/leave-request.service.ts',
    'src/modules/therapy/services/conflict-detection.service.ts',
    'src/modules/therapy/services/recurrence.service.ts',
    'src/modules/therapy/services/therapy-billing.service.ts',
    'src/modules/therapy/services/group.service.ts',
    'src/shared/money/**/*.ts',
    'src/shared/guards/**/*.ts',
    '!src/**/*.spec.ts',
  ],
  thresholds: { high: 80, low: 75, break: 50 },
  jest: {
    projectType: 'custom',
    configFile: 'jest.config.js',
  },
};
